### ISSUE TITLE
Redis Error - LOADING Redis is loading the dataset in memory

### ISSUE THREAD

**Issue by torbentschechne** [spinupwp/spinupwp-plugin#46]
Hello,
I have more and more servers with this error:

```
381719 FastCGI sent in stderr: "PHP message: RedisException: LOADING Redis is loading the dataset in memory in /sites/domain/files/wp-content/object-cache.php:418
Stack trace:
#0 /sites/domain/files/wp-content/object-cache.php(418): Redis->ping()
#1 /sites/domain/files/wp-content/object-cache.php(155): WP_Object_Cache->__construct(true)
#2 /sites/domain/files/wp-includes/load.php(701): wp_cache_init()
#3 /sites/domain/files/wp-settings.php(131): wp_start_object_cache()
#4 /sites/domain/files/wp-config.php(100): require_once('/sites/domain...')
#5 /sites/domain/files/wp-load.php(37): require_once('/sites/domain...')
#6 /sites/domain/files/wp-blog-header.php(13): require_once('/sites/domain...')
#7 /sites/domain/files/index.php(17): require('/sites/domain...')
```

What can I do about it? The only solution I found so far is, to define `define( 'WP_REDIS_DISABLED', true );`, but this can't be right...

**Comment by Jamesclark32** [comment]
This error message suggests Redis is in process of restarting at the time the plugin tried to interact with the object cache. 

If anyone is seeing this frequently, it means Redis is restarting frequently,  likely resulting in relevant error messages in the Redis error log. It's most likely that the server is often running out of memory and the 'Out of Memory Killer' is terminating Redis.

@torbentschechne I realize this issue is dated. If you are continuing to see problems like this please reach out in our [support channel](https://spinupwp.com/pricing/#support) and we can help figure out what's going on!
